- name: Create Pod for running evicted pod cleaner script
  k8s:
    state: present
    namespace: default
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: evicted-pod-cleaner
      spec:
        containers:
        - name: clean-evicted-pods
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
          - /bin/bash /scripts/clean-evicted-pods.sh
          volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: evicted-pod-cleaner-logs
            mountPath: /var/log/evicted-pod-cleaner
        volumes:
        - name: scripts
          configMap:
            name: evicted-pod-cleaner
        - name: evicted-pod-cleaner-logs
          persistentVolumeClaim:
            claimName: evicted-pod-log
