---
- name: Delete Evicted Pods
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: Pre_works
      name: create PVC, ClusterRole, Account, Binding
    - role: create_configmap
    - role: create_cronjob
    - role: create_job
