- name: Create CronJob for running evicted pod cleaner script periodically
  k8s:
    state: present
    namespace: default
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: evicted-pod-cleaner
      spec:
        schedule: "*/5 * * * *"
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                - name: clean-evicted-pods
                  image: evicted-pod-cleaner
                  command: ["/bin/sh", "-c"]
                  args:
                  - /bin/bash /scripts/clean-evicted-pods.sh
                  volumeMounts:
                  - name: scripts
                    mountPath: /scripts
                  - name: logs
                    mountPath: /logs
                restartPolicy: OnFailure
                volumes:
                - name: scripts
                  configMap:
                    name: evicted-pod-cleaner
                - name: logs
                  persistentVolumeClaim:
                    claimName: evicted-pod-log
